### ISSUE TITLE
printvars is broken in Make 4.3 preventing use of this tool on modern OS's

### ISSUE THREAD

**Issue by alex-arseneau** [TimesysGit/vigiles-buildroot#4]
This tool relies on the printvars feature of Make. Starting in 4.3 printvars has been disabled and returns an error preventing generation of the vigiles report.

https://lore.kernel.org/all/20220101214034.2152144-1-giulio.benetti@benettiengineering.com/T/

**Comment by iancampbell** [comment]
A workaround for operating systems that use Make 4.3 has been added to resolve this issue.
https://github.com/TimesysGit/vigiles-buildroot/commit/dcb4f0c9c64b72c6f641f581d7a3d14e8679d0cd
